import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import PptxGenJS from 'pptxgenjs'
import { Document, Packer, Paragraph, TextRun, AlignmentType } from 'docx'
import { SLIDE_TEMPLATES, TemplateId } from '@/lib/slide-templates'

export async function POST(request: NextRequest) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const body = await request.json()
  const { slides, projectName, format, templateId = 'modern' } = body

  if (!slides || !format) {
    return NextResponse.json({ error: 'Slides and format are required' }, { status: 400 })
  }

  if (!['pptx', 'docx'].includes(format)) {
    return NextResponse.json({ error: 'Invalid format. Only PPTX and DOCX are supported.' }, { status: 400 })
  }

  const template = SLIDE_TEMPLATES[templateId as TemplateId] || SLIDE_TEMPLATES.modern
  const colors = template.styles.colors

  try {
    let fileBuffer: Buffer
    let contentType: string
    let fileExtension: string

    if (format === 'pptx') {
      fileBuffer = await generatePPTX(slides, projectName || 'Presentation', template)
      contentType = 'application/vnd.openxmlformats-officedocument.presentationml.presentation'
      fileExtension = 'pptx'
    } else {
      fileBuffer = await generateDOCX(slides, projectName || 'Presentation', colors)
      contentType = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
      fileExtension = 'docx'
    }

    return new NextResponse(new Uint8Array(fileBuffer), {
      headers: {
        'Content-Type': contentType,
        'Content-Disposition': `attachment; filename="${projectName || 'presentation'}.${fileExtension}"`,
      },
    })
  } catch (error) {
    console.error('Export error:', error)
    return NextResponse.json({ error: 'Failed to generate export' }, { status: 500 })
  }
}

// ----- PPTX Generator (Fixed) -----
async function generatePPTX(slides: any[], title: string, template: any): Promise<Buffer> {
  const colors = template.styles.colors
  const pptx = new PptxGenJS()
  pptx.defineLayout({ name: 'WIDE', width: 13.33, height: 7.5 })
  pptx.layout = 'WIDE'

  const sanitize = (text: string): string => {
    if (!text) return ''
    let cleaned = text.replace(/[\x00-\x09\x0B-\x1F\x7F]/g, '')
    cleaned = cleaned.replace(/[💡✅▶✔🎨✨📚💼🌿🌙]/g, (match) => {
      const map: Record<string, string> = {
        '💡': '(Tip)',
        '✅': '[✓]',
        '▶': '▸',
        '✔': '[✓]',
        '🎨': '[Art]',
        '✨': '[Star]',
        '📚': '[Book]',
        '💼': '[Briefcase]',
        '🌿': '[Leaf]',
        '🌙': '[Moon]',
      }
      return map[match] || match
    })
    return cleaned
  }

  // Title Slide
  const titleSlide = pptx.addSlide()
  titleSlide.background = { color: colors.bg }

  if (template.styles.titleSlide.decoration === 'bar') {
    titleSlide.addShape(pptx.ShapeType.rect, {
      x: 2, y: 5.5, w: 9.33, h: 0.2,
      fill: { color: colors.accent },
      line: { color: colors.accent },
    })
  } else if (template.styles.titleSlide.decoration === 'circle') {
    titleSlide.addShape(pptx.ShapeType.ellipse, {
      x: 8, y: 0, w: 4, h: 4,
      fill: { color: colors.accent },
      line: { color: colors.accent },
    })
  }

  titleSlide.addText(sanitize(title), {
    x: 0.5, y: 1.5, w: 12.33, h: 2,
    fontSize: template.styles.titleSlide.titleFontSize,
    color: colors.text, bold: true,
    align: template.styles.titleSlide.alignment,
  })
  titleSlide.addText('Generated by EduGuide AI+', {
    x: 0.5, y: 4.5, w: 12.33, h: 1,
    fontSize: template.styles.titleSlide.subtitleFontSize,
    color: '6B7280',
    align: template.styles.titleSlide.alignment,
  })

  // Content Slides
  slides.forEach((slideData: any, idx: number) => {
    const slide = pptx.addSlide()
    slide.background = { color: colors.bg }

    if (template.styles.contentSlide.accentPosition === 'top') {
      slide.addShape(pptx.ShapeType.rect, {
        x: 0, y: 0, w: 13.33, h: 0.4,
        fill: { color: colors.primary },
        line: { color: colors.primary },
      })
    }
    if (template.styles.contentSlide.accentPosition === 'left') {
      slide.addShape(pptx.ShapeType.rect, {
        x: 0, y: 0, w: 0.3, h: 7.5,
        fill: { color: colors.accent },
        line: { color: colors.accent },
      })
    }

    const titleX = template.styles.contentSlide.accentPosition === 'left' ? 0.7 : 0.5
    slide.addText(sanitize(slideData.title || `Slide ${idx + 1}`), {
      x: titleX, y: 0.5, w: 11, h: 0.8,
      fontSize: 28, color: colors.text, bold: true,
    })

    const bullets = slideData.bullets || ['No bullet points provided.']
    let yPos = 1.8
    const bulletStyle = template.styles.contentSlide.bulletStyle
    let prefix: string | ((i: number) => string) = '• '
    if (bulletStyle === 'arrow') prefix = '▸ '
    else if (bulletStyle === 'check') prefix = '✓ '
    else if (bulletStyle === 'number') prefix = (i: number) => `${i + 1}. `
    else prefix = '• '

    bullets.forEach((bullet: string, i: number) => {
      if (i > 7) return
      const p = typeof prefix === 'function' ? prefix(i) : prefix
      slide.addText(`${p}${sanitize(bullet)}`, {
        x: titleX + 0.5, y: yPos, w: 10.5, h: 0.7,
        fontSize: 17, color: colors.text,
        valign: 'middle',
        align: template.styles.contentSlide.alignment,
      })
      yPos += 0.75
    })

    if (slideData.key_takeaway) {
      const takeawayY = Math.min(yPos + 0.5, 6.2)
      slide.addShape(pptx.ShapeType.rect, {
        x: 1.5, y: takeawayY, w: 10, h: 0.8,
        fill: { color: 'FEF3C7' },
        line: { color: 'FCD34D' },
        rectRadius: 2,
      })
      slide.addText(`💡 ${sanitize(slideData.key_takeaway)}`, {
        x: 1.8, y: takeawayY + 0.1, w: 9.5, h: 0.6,
        fontSize: 14, color: '92400E', italic: true,
        align: 'justify',
      })
    }

    slide.addText(`${idx + 1} / ${slides.length}`, {
      x: 11.5, y: 7, w: 1.5, h: 0.4,
      fontSize: 12, color: '9CA3AF', align: 'right',
    })
  })

  // ✅ FIXED: return buffer directly
  const buffer = await pptx.write({ outputType: 'nodebuffer' })
  return buffer as Buffer   // ✅ Red line khatam
}

// ----- DOCX Generator -----
async function generateDOCX(slides: any[], title: string, colors: any): Promise<Buffer> {
  const doc = new Document({
    sections: [{
      properties: {},
      children: [
        new Paragraph({
          children: [new TextRun({ text: title, size: 48, bold: true, color: colors.primary, font: 'Calibri' })],
          alignment: AlignmentType.CENTER,
          spacing: { after: 400 },
        }),
        new Paragraph({
          children: [new TextRun({ text: 'Generated by EduGuide AI+', size: 24, color: '6B7280', font: 'Calibri' })],
          alignment: AlignmentType.CENTER,
          spacing: { after: 600 },
        }),
        ...slides.flatMap((slideData: any, idx: number) => {
          const paragraphs: Paragraph[] = []
          paragraphs.push(
            new Paragraph({
              children: [new TextRun({ text: `Slide ${idx + 1}: ${slideData.title || 'Untitled'}`, size: 28, bold: true, color: colors.text, font: 'Calibri' })],
              spacing: { before: 400, after: 200 },
            })
          )
          const bullets = slideData.bullets || ['No bullet points.']
          bullets.forEach((bullet: string) => {
            paragraphs.push(
              new Paragraph({
                children: [new TextRun({ text: `●  ${bullet}`, size: 22, color: colors.text, font: 'Calibri' })],
                spacing: { after: 100 },
                bullet: { level: 0 },
                alignment: AlignmentType.JUSTIFIED,
              })
            )
          })
          if (slideData.key_takeaway) {
            paragraphs.push(
              new Paragraph({
                children: [new TextRun({ text: `💡 ${slideData.key_takeaway}`, size: 18, color: '92400E', font: 'Calibri', italics: true })],
                spacing: { before: 200, after: 200 },
                alignment: AlignmentType.JUSTIFIED,
              })
            )
          }
          if (idx < slides.length - 1) {
            paragraphs.push(
              new Paragraph({
                children: [new TextRun({ text: '═══════════════════════════════════════════════', size: 14, color: 'E5E7EB' })],
                spacing: { before: 300 },
              })
            )
          }
          return paragraphs
        }),
      ],
    }],
  })
  const buffer = await Packer.toBuffer(doc)
  return buffer
}