import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import PptxGenJS from 'pptxgenjs'
import { Document, Packer, Paragraph, TextRun, AlignmentType } from 'docx'
import { Buffer } from 'buffer'

// Template color schemes (matching frontend templates)
const TEMPLATES: Record<string, any> = {
  modern: {
    colors: { bg: 'F8FAFC', accent: '6366F1', title: '1E293B', text: '334155' },
  },
  creative: {
    colors: { bg: 'FDF4FF', accent: 'D946EF', title: '4C1D95', text: '5B21B6' },
  },
  professional: {
    colors: { bg: 'FFFFFF', accent: '0F172A', title: '0F172A', text: '1E293B' },
  },
  organic: {
    colors: { bg: 'F0FDF4', accent: '059669', title: '064E3B', text: '047857' },
  },
  dark: {
    colors: { bg: '0F0F1A', accent: 'A78BFA', title: 'FFFFFF', text: 'D1D5DB' },
  },
}

export async function POST(request: NextRequest) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const body = await request.json()
  const { slides, projectName, format, templateId = 'modern' } = body

  if (!slides || !format) {
    return NextResponse.json({ error: 'Slides and format are required' }, { status: 400 })
  }

  // ✅ Only allow PPTX and DOCX (PDF removed to avoid build issues)
  if (!['pptx', 'docx'].includes(format)) {
    return NextResponse.json({ error: 'Invalid format. Only PPTX and DOCX are supported.' }, { status: 400 })
  }

  const template = TEMPLATES[templateId] || TEMPLATES.modern
  const colors = template.colors

  try {
    let fileBuffer: Buffer
    let contentType: string
    let fileExtension: string

    if (format === 'pptx') {
      fileBuffer = await generatePPTX(slides, projectName || 'Presentation', colors)
      contentType = 'application/vnd.openxmlformats-officedocument.presentationml.presentation'
      fileExtension = 'pptx'
    } else { // docx
      fileBuffer = await generateDOCX(slides, projectName || 'Presentation', colors)
      contentType = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
      fileExtension = 'docx'
    }

    return new NextResponse(new Uint8Array(fileBuffer), {
      headers: {
        'Content-Type': contentType,
        'Content-Disposition': `attachment; filename="${projectName || 'presentation'}.${fileExtension}"`,
      },
    })
  } catch (error) {
    console.error('Export error:', error)
    return NextResponse.json({ error: 'Failed to generate export' }, { status: 500 })
  }
}

// ----- PPTX Generator -----
async function generatePPTX(slides: any[], title: string, colors: any): Promise<Buffer> {
  const pptx = new PptxGenJS()
  pptx.defineLayout({ name: 'WIDE', width: 13.33, height: 7.5 })
  pptx.layout = 'WIDE'

  // Title Slide
  const titleSlide = pptx.addSlide()
  titleSlide.background = { color: colors.bg }
  titleSlide.addText(title, {
    x: 0.5, y: 1.5, w: 12, h: 1.5,
    fontSize: 44, fontFace: 'Arial', color: colors.title, bold: true, align: 'center',
  })
  titleSlide.addText('Generated by EduGuide AI+', {
    x: 0.5, y: 3.5, w: 12, h: 0.8,
    fontSize: 20, fontFace: 'Arial', color: '6B7280', align: 'center',
  })

  // Content Slides
  slides.forEach((slideData: any, idx: number) => {
    const slide = pptx.addSlide()
    slide.background = { color: colors.bg }

    // Left accent bar
    slide.addShape(pptx.ShapeType.rect, {
      x: 0, y: 0, w: 0.3, h: 7.5,
      fill: { color: colors.accent }, line: { color: colors.accent },
    })

    // Title
    slide.addText(slideData.title || `Slide ${idx + 1}`, {
      x: 0.7, y: 0.5, w: 11, h: 0.8,
      fontSize: 28, fontFace: 'Arial', color: colors.title, bold: true,
    })

    // Bullets
    const bullets = slideData.bullets || ['No bullet points provided.']
    let yPos = 1.8
    bullets.forEach((bullet: string, i: number) => {
      if (i > 7) return
      slide.addText(`▶  ${bullet}`, {
        x: 1.2, y: yPos, w: 10.5, h: 0.7,
        fontSize: 17, fontFace: 'Arial', color: colors.text,
        valign: 'middle', align: 'justify',
      })
      yPos += 0.75
    })

    // Key Takeaway
    if (slideData.key_takeaway) {
      slide.addShape(pptx.ShapeType.rect, {
        x: 1.2, y: 6.2, w: 10, h: 0.8,
        fill: { color: 'FEF3C7' }, line: { color: 'FCD34D' },
      })
      slide.addText(`💡 ${slideData.key_takeaway}`, {
        x: 1.5, y: 6.3, w: 9.5, h: 0.6,
        fontSize: 14, fontFace: 'Arial', color: '92400E', italic: true, align: 'justify',
      })
    }

    // Slide number
    slide.addText(`${idx + 1} / ${slides.length}`, {
      x: 11.5, y: 7, w: 1.5, h: 0.4,
      fontSize: 12, fontFace: 'Arial', color: '9CA3AF', align: 'right',
    })
  })

  // ✅ FIX: return buffer as Buffer (type assertion)
  const buffer = await pptx.write({ outputType: 'nodebuffer' })
  return Buffer.from(buffer as any)
}

// ----- DOCX Generator -----
async function generateDOCX(slides: any[], title: string, colors: any): Promise<Buffer> {
  const doc = new Document({
    sections: [{
      properties: {},
      children: [
        new Paragraph({
          children: [new TextRun({ text: title, size: 48, bold: true, color: colors.title, font: 'Calibri' })],
          alignment: AlignmentType.CENTER,
          spacing: { after: 400 },
        }),
        new Paragraph({
          children: [new TextRun({ text: 'Generated by EduGuide AI+', size: 24, color: '6B7280', font: 'Calibri' })],
          alignment: AlignmentType.CENTER,
          spacing: { after: 600 },
        }),
        ...slides.flatMap((slideData: any, idx: number) => {
          const paragraphs: Paragraph[] = []

          paragraphs.push(
            new Paragraph({
              children: [new TextRun({ text: `Slide ${idx + 1}: ${slideData.title || 'Untitled'}`, size: 28, bold: true, color: colors.title, font: 'Calibri' })],
              spacing: { before: 400, after: 200 },
            })
          )

          const bullets = slideData.bullets || ['No bullet points provided.']
          bullets.forEach((bullet: string) => {
            paragraphs.push(
              new Paragraph({
                children: [new TextRun({ text: `●  ${bullet}`, size: 22, color: colors.text, font: 'Calibri' })],
                spacing: { after: 100 },
                bullet: { level: 0 },
                alignment: AlignmentType.JUSTIFIED,
              })
            )
          })

          if (slideData.key_takeaway) {
            paragraphs.push(
              new Paragraph({
                children: [new TextRun({ text: `💡 ${slideData.key_takeaway}`, size: 18, color: '92400E', font: 'Calibri', italics: true })],
                spacing: { before: 200, after: 200 },
                alignment: AlignmentType.JUSTIFIED,
              })
            )
          }

          if (idx < slides.length - 1) {
            paragraphs.push(
              new Paragraph({
                children: [new TextRun({ text: '═══════════════════════════════════════════════', size: 14, color: 'E5E7EB' })],
                spacing: { before: 300 },
              })
            )
          }

          return paragraphs
        }),
      ],
    }],
  })

  const buffer = await Packer.toBuffer(doc)
  return Buffer.from(buffer)
}