import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import PptxGenJS from 'pptxgenjs'
import { SLIDE_TEMPLATES, TemplateId } from '@/lib/slide-templates'

// ============================================================
// ✅ TOP-LEVEL HELPER (accessible to all functions)
// ============================================================
const clean = (text: string): string => {
    if (!text) return ''
    return String(text)
        .replace(/[\x00-\x1F\x7F]/g, '')
        .replace(/[\u{1F300}-\u{1F9FF}]/gu, '')
        .trim()
}

export async function POST(request: NextRequest) {
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) {
        return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const body = await request.json()
    const { templateId, slides, title } = body

    if (!templateId || !slides || !title) {
        return NextResponse.json({ error: 'Template, slides, and title required' }, { status: 400 })
    }

    const template = SLIDE_TEMPLATES[templateId as TemplateId] || SLIDE_TEMPLATES.modern

    try {
        const buffer = await generateDesignerPPTX(slides, title, template)
        return new NextResponse(new Uint8Array(buffer), {
            headers: {
                'Content-Type': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
                'Content-Disposition': `attachment; filename="${title.replace(/\s+/g, '_')}.pptx"`,
            },
        })
    } catch (error: any) {
        console.error('Export error:', error)
        return NextResponse.json({ error: error.message || 'Failed' }, { status: 500 })
    }
}

async function generateDesignerPPTX(slides: any[], title: string, template: any): Promise<Buffer> {
    const colors = template.styles.colors
    const styles = template.styles
    const pptx = new PptxGenJS()
    pptx.defineLayout({ name: 'WIDE', width: 13.33, height: 7.5 })
    pptx.layout = 'WIDE'

    // ============================================================
    // TITLE SLIDE
    // ============================================================
    const titleSlide = pptx.addSlide()
    titleSlide.background = { color: colors.bg }

    if (styles.titleSlide.decoration === 'bar') {
        titleSlide.addShape(pptx.ShapeType.rect, {
            x: 0, y: 0, w: 13.33, h: 3,
            fill: { color: colors.accent }, line: { color: colors.accent },
        })
        titleSlide.addShape(pptx.ShapeType.rect, {
            x: 0, y: 3, w: 13.33, h: 0.1,
            fill: { color: colors.secondary }, line: { color: colors.secondary },
        })
        titleSlide.addText(clean(title), {
            x: 0.5, y: 0.7, w: 12, h: 1.8,
            fontSize: 44, color: 'FFFFFF', bold: true,
            align: 'center', valign: 'middle', fontFace: 'Arial',
        })
        titleSlide.addText('Generated by EduGuide AI+', {
            x: 0.5, y: 3.7, w: 12.33, h: 1,
            fontSize: 20, color: colors.text,
            align: 'center', fontFace: 'Arial',
        })
        titleSlide.addShape(pptx.ShapeType.rect, {
            x: 5, y: 5.5, w: 3.33, h: 0.1,
            fill: { color: colors.accent }, line: { color: colors.accent },
        })
    } else if (styles.titleSlide.decoration === 'circle') {
        titleSlide.addShape(pptx.ShapeType.ellipse, {
            x: -1.5, y: -1.5, w: 6, h: 6,
            fill: { color: colors.secondary }, line: { color: colors.secondary },
        })
        titleSlide.addShape(pptx.ShapeType.ellipse, {
            x: 9.5, y: 3.5, w: 5, h: 5,
            fill: { color: colors.secondary }, line: { color: colors.secondary },
        })
        titleSlide.addText(clean(title), {
            x: 0.5, y: 2.5, w: 12.33, h: 2,
            fontSize: 48, color: colors.text, bold: true,
            align: 'center', valign: 'middle', fontFace: 'Arial',
        })
        titleSlide.addText('Generated by EduGuide AI+', {
            x: 0.5, y: 4.8, w: 12.33, h: 0.8,
            fontSize: 20, color: colors.text,
            align: 'center', fontFace: 'Arial',
        })
    } else {
        titleSlide.addText(clean(title), {
            x: 1, y: 2, w: 11.33, h: 2,
            fontSize: 44, color: colors.text, bold: true,
            align: 'left', valign: 'middle', fontFace: 'Arial',
        })
        titleSlide.addText('Generated by EduGuide AI+', {
            x: 1, y: 4.2, w: 11.33, h: 0.8,
            fontSize: 18, color: colors.primary,
            align: 'left', fontFace: 'Arial',
        })
        titleSlide.addShape(pptx.ShapeType.rect, {
            x: 1, y: 5.2, w: 3, h: 0.06,
            fill: { color: colors.accent }, line: { color: colors.accent },
        })
    }

    // ============================================================
    // CONTENT SLIDES
    // ============================================================
    for (let idx = 0; idx < slides.length; idx++) {
        const slide = slides[idx]
        const type = slide.type || 'content'

        const s = pptx.addSlide()
        s.background = { color: colors.bg }

        if (styles.contentSlide.accentPosition === 'left') {
            s.addShape(pptx.ShapeType.rect, {
                x: 0, y: 0, w: 0.25, h: 7.5,
                fill: { color: colors.accent }, line: { color: colors.accent },
            })
        } else if (styles.contentSlide.accentPosition === 'top') {
            s.addShape(pptx.ShapeType.rect, {
                x: 0, y: 0, w: 13.33, h: 0.4,
                fill: { color: colors.accent }, line: { color: colors.accent },
            })
        }

        const titleY = styles.contentSlide.accentPosition === 'top' ? 0.7 : 0.5

        if (styles.contentSlide.accentPosition === 'left') {
            s.addShape(pptx.ShapeType.rect, {
                x: 0.5, y: 0.5, w: 0.9, h: 0.6,
                fill: { color: colors.accent }, line: { color: colors.accent },
            })
            s.addText(String(idx + 1).padStart(2, '0'), {
                x: 0.5, y: 0.5, w: 0.9, h: 0.6,
                fontSize: 18, color: 'FFFFFF', bold: true,
                align: 'center', valign: 'middle', fontFace: 'Arial',
            })
        }

        const actualTitleX = styles.contentSlide.accentPosition === 'left' ? 1.7 : 0.5
        s.addText(clean(slide.title || `Slide ${idx + 1}`), {
            x: actualTitleX, y: titleY, w: 11, h: 0.9,
            fontSize: 28, color: colors.text, bold: true,
            fontFace: 'Arial', valign: 'middle',
        })
        s.addShape(pptx.ShapeType.rect, {
            x: actualTitleX, y: titleY + 0.9, w: 1.8, h: 0.06,
            fill: { color: colors.accent }, line: { color: colors.accent },
        })

        // Render slide body
        switch (type) {
            case 'chart':
                renderChartSlide(s, slide, colors, actualTitleX)
                break
            case 'stats':
                renderStatsSlide(s, slide, colors, actualTitleX)
                break
            case 'process':
                renderProcessSlide(s, slide, colors, actualTitleX)
                break
            case 'comparison':
                renderComparisonSlide(s, slide, colors, actualTitleX)
                break
            case 'quote':
                renderQuoteSlide(s, slide, colors, actualTitleX)
                break
            case 'icon-grid':
                renderIconGridSlide(s, slide, colors, actualTitleX)
                break
            default:
                renderContentSlide(s, slide, colors, styles, actualTitleX)
        }

        // Key Takeaway
        if (slide.key_takeaway) {
            s.addShape(pptx.ShapeType.rect, {
                x: actualTitleX, y: 6.5, w: 11.8, h: 0.6,
                fill: { color: 'FEF3C7' },
                line: { color: colors.accent, width: 0.5 },
            })
            s.addText(`TIP: ${clean(slide.key_takeaway)}`, {
                x: actualTitleX + 0.2, y: 6.5, w: 11.4, h: 0.6,
                fontSize: 11, color: '92400E', italic: true,
                valign: 'middle', fontFace: 'Arial',
            })
        }

        s.addText(`${idx + 1} / ${slides.length}`, {
            x: 11.5, y: 7.2, w: 1.5, h: 0.3,
            fontSize: 10, color: '9CA3AF',
            align: 'right', fontFace: 'Arial',
        })
    }

    // ============================================================
    // END SLIDE
    // ============================================================
    const endSlide = pptx.addSlide()
    endSlide.background = { color: colors.accent }
    endSlide.addText('Thank You', {
        x: 0.5, y: 2.5, w: 12.33, h: 1.5,
        fontSize: 54, color: 'FFFFFF', bold: true,
        align: 'center', valign: 'middle', fontFace: 'Arial',
    })
    endSlide.addText('Presented by EduGuide AI+', {
        x: 0.5, y: 4.5, w: 12.33, h: 0.8,
        fontSize: 20, color: 'FFFFFF',
        align: 'center', fontFace: 'Arial',
    })

    const buffer = await pptx.write({ outputType: 'nodebuffer' })
    return buffer as Buffer
}

// ============================================================
// LAYOUT 1: CHART SLIDE
// ============================================================
function renderChartSlide(s: any, slide: any, colors: any, x: number) {
    const chartData = (slide.chartData || []).slice(0, 8)
    if (chartData.length === 0) return

    const labels = chartData.map((d: any) => clean(d.label))
    const values = chartData.map((d: any) => Number(d.value) || 0)
    const chartType = slide.chartType || 'bar'

    let pptxChartType: any
    switch (chartType) {
        case 'pie': pptxChartType = 'pie'; break
        case 'line': pptxChartType = 'line'; break
        case 'doughnut': pptxChartType = 'doughnut'; break
        default: pptxChartType = 'bar'
    }

    const data = [{
        name: clean(slide.title || 'Data'),
        labels: labels,
        values: values,
    }]

    s.addChart(pptxChartType, data, {
        x: x,
        y: 2.2,
        w: 11.5,
        h: 4.0,
        showLegend: true,
        legendPos: 'b',
        showValue: true,
        chartColors: [
            colors.accent,
            colors.secondary,
            colors.primary,
            '6366F1',
            'EC4899',
            'F97316',
            '10B981',
            '8B5CF6',
        ],
    })
}

// ============================================================
// LAYOUT 2: STATS SLIDE
// ============================================================
function renderStatsSlide(s: any, slide: any, colors: any, x: number) {
    const stats = (slide.stats || []).slice(0, 4)
    if (stats.length === 0) return

    const count = stats.length
    const gap = 0.4
    const totalWidth = 11.8
    const cardW = (totalWidth - gap * (count - 1)) / count
    const startY = 2.4

    stats.forEach((stat: any, i: number) => {
        const cardX = x + i * (cardW + gap)

        s.addShape('rect', {
            x: cardX, y: startY, w: cardW, h: 3.2,
            fill: { color: colors.cardBg || 'FFFFFF' },
            line: { color: colors.accent, width: 1.5 },
        })
        s.addShape('rect', {
            x: cardX, y: startY, w: cardW, h: 0.15,
            fill: { color: colors.accent }, line: { color: colors.accent },
        })
        s.addText(clean(stat.value || '0'), {
            x: cardX, y: startY + 0.6, w: cardW, h: 1.5,
            fontSize: 54, color: colors.accent, bold: true,
            align: 'center', valign: 'middle', fontFace: 'Arial',
        })
        s.addText(clean(stat.label || ''), {
            x: cardX, y: startY + 2.2, w: cardW, h: 0.8,
            fontSize: 16, color: colors.text,
            align: 'center', valign: 'middle', fontFace: 'Arial',
        })
    })
}

// ============================================================
// LAYOUT 3: PROCESS FLOW
// ============================================================
function renderProcessSlide(s: any, slide: any, colors: any, x: number) {
    const steps = (slide.steps || []).slice(0, 5)
    if (steps.length === 0) return

    const count = steps.length
    const circleSize = 0.9
    const gap = (11.5 - circleSize * count) / (count + 1)
    const yCenter = 3.4

    if (count > 1) {
        const lineStartX = x + gap + circleSize / 2
        const lineEndX = x + gap + (circleSize + gap) * (count - 1) + circleSize / 2
        s.addShape('rect', {
            x: lineStartX, y: yCenter + circleSize / 2 - 0.03,
            w: lineEndX - lineStartX, h: 0.06,
            fill: { color: colors.accent }, line: { color: colors.accent },
        })
    }

    steps.forEach((step: string, i: number) => {
        const circleX = x + gap + i * (circleSize + gap)

        s.addShape('ellipse', {
            x: circleX, y: yCenter, w: circleSize, h: circleSize,
            fill: { color: colors.accent }, line: { color: colors.accent },
        })
        s.addText(String(i + 1), {
            x: circleX, y: yCenter, w: circleSize, h: circleSize,
            fontSize: 28, color: 'FFFFFF', bold: true,
            align: 'center', valign: 'middle', fontFace: 'Arial',
        })
        s.addText(clean(step), {
            x: circleX - 0.6, y: yCenter + circleSize + 0.2, w: circleSize + 1.2, h: 1.5,
            fontSize: 12, color: colors.text,
            align: 'center', valign: 'top', fontFace: 'Arial',
        })
    })
}

// ============================================================
// LAYOUT 4: COMPARISON
// ============================================================
function renderComparisonSlide(s: any, slide: any, colors: any, x: number) {
    const halfW = 5.6
    const gap = 0.6

    s.addShape('rect', {
        x: x, y: 2.2, w: halfW, h: 4.1,
        fill: { color: colors.cardBg || 'FFFFFF' },
        line: { color: colors.accent, width: 1.5 },
    })
    s.addShape('rect', {
        x: x, y: 2.2, w: halfW, h: 0.7,
        fill: { color: colors.accent }, line: { color: colors.accent },
    })
    s.addText(clean(slide.leftTitle || 'Option A'), {
        x: x, y: 2.2, w: halfW, h: 0.7,
        fontSize: 20, color: 'FFFFFF', bold: true,
        align: 'center', valign: 'middle', fontFace: 'Arial',
    })

        ; (slide.leftItems || []).slice(0, 6).forEach((item: string, i: number) => {
            s.addText(`• ${clean(item)}`, {
                x: x + 0.3, y: 3.1 + i * 0.55, w: halfW - 0.6, h: 0.5,
                fontSize: 13, color: colors.text,
                valign: 'middle', fontFace: 'Arial',
            })
        })

    const rightX = x + halfW + gap
    s.addShape('rect', {
        x: rightX, y: 2.2, w: halfW, h: 4.1,
        fill: { color: colors.cardBg || 'FFFFFF' },
        line: { color: colors.secondary, width: 1.5 },
    })
    s.addShape('rect', {
        x: rightX, y: 2.2, w: halfW, h: 0.7,
        fill: { color: colors.secondary }, line: { color: colors.secondary },
    })
    s.addText(clean(slide.rightTitle || 'Option B'), {
        x: rightX, y: 2.2, w: halfW, h: 0.7,
        fontSize: 20, color: 'FFFFFF', bold: true,
        align: 'center', valign: 'middle', fontFace: 'Arial',
    })

        ; (slide.rightItems || []).slice(0, 6).forEach((item: string, i: number) => {
            s.addText(`• ${clean(item)}`, {
                x: rightX + 0.3, y: 3.1 + i * 0.55, w: halfW - 0.6, h: 0.5,
                fontSize: 13, color: colors.text,
                valign: 'middle', fontFace: 'Arial',
            })
        })

    const vsX = x + halfW + gap / 2 - 0.4
    s.addShape('ellipse', {
        x: vsX, y: 3.9, w: 0.8, h: 0.8,
        fill: { color: colors.primary }, line: { color: colors.primary },
    })
    s.addText('VS', {
        x: vsX, y: 3.9, w: 0.8, h: 0.8,
        fontSize: 14, color: 'FFFFFF', bold: true,
        align: 'center', valign: 'middle', fontFace: 'Arial',
    })
}

// ============================================================
// LAYOUT 5: QUOTE SLIDE
// ============================================================
function renderQuoteSlide(s: any, slide: any, colors: any, x: number) {
    s.addText('"', {
        x: x - 0.2, y: 1.8, w: 2, h: 2,
        fontSize: 120, color: colors.accent, bold: true,
        align: 'left', valign: 'top', fontFace: 'Arial',
    })

    s.addText(clean(slide.quote || ''), {
        x: x + 1, y: 2.8, w: 10.5, h: 2.5,
        fontSize: 24, color: colors.text, italic: true,
        align: 'center', valign: 'middle', fontFace: 'Arial',
    })

    if (slide.author) {
        s.addShape('rect', {
            x: x + 4.5, y: 5.6, w: 3, h: 0.05,
            fill: { color: colors.accent }, line: { color: colors.accent },
        })
        s.addText(`— ${clean(slide.author)}`, {
            x: x, y: 5.8, w: 11.8, h: 0.6,
            fontSize: 16, color: colors.accent, bold: true,
            align: 'center', valign: 'middle', fontFace: 'Arial',
        })
    }
}

// ============================================================
// LAYOUT 6: ICON GRID
// ============================================================
function renderIconGridSlide(s: any, slide: any, colors: any, x: number) {
    const items = (slide.items || []).slice(0, 6)
    if (items.length === 0) return

    const cols = 3
    const cellW = 3.7
    const cellH = 1.9
    const gapX = 0.35
    const gapY = 0.3
    const startY = 2.3

    items.forEach((item: any, i: number) => {
        const row = Math.floor(i / cols)
        const col = i % cols
        const cellX = x + col * (cellW + gapX)
        const cellY = startY + row * (cellH + gapY)

        s.addShape('rect', {
            x: cellX, y: cellY, w: cellW, h: cellH,
            fill: { color: colors.cardBg || 'FFFFFF' },
            line: { color: colors.accent, width: 1 },
        })

        s.addShape('ellipse', {
            x: cellX + 0.2, y: cellY + 0.45, w: 0.9, h: 0.9,
            fill: { color: colors.accent }, line: { color: colors.accent },
        })
        s.addText(clean(item.icon || '●'), {
            x: cellX + 0.2, y: cellY + 0.45, w: 0.9, h: 0.9,
            fontSize: 24, color: 'FFFFFF', bold: true,
            align: 'center', valign: 'middle', fontFace: 'Arial',
        })

        s.addText(clean(item.label || ''), {
            x: cellX + 1.25, y: cellY, w: cellW - 1.4, h: cellH,
            fontSize: 14, color: colors.text, bold: true,
            align: 'left', valign: 'middle', fontFace: 'Arial',
        })
    })
}

// ============================================================
// LAYOUT 7: CONTENT (default)
// ============================================================
function renderContentSlide(s: any, slide: any, colors: any, styles: any, x: number) {
    const bullets = (slide.bullets || ['No content']).slice(0, 8)
    const bulletStyle = styles.contentSlide.bulletStyle
    let prefixChar = '• '
    if (bulletStyle === 'arrow') prefixChar = '▸ '
    else if (bulletStyle === 'check') prefixChar = '✓ '

    let yPos = 2.2
    bullets.forEach((bullet: string, i: number) => {
        const prefix = bulletStyle === 'number' ? `${i + 1}. ` : prefixChar

        if (bulletStyle === 'arrow' || bulletStyle === 'check') {
            s.addText(prefix.trim(), {
                x: x, y: yPos, w: 0.4, h: 0.6,
                fontSize: 18, color: colors.accent, bold: true,
                valign: 'middle', fontFace: 'Arial',
            })
            s.addText(clean(bullet), {
                x: x + 0.4, y: yPos, w: 11.3, h: 0.6,
                fontSize: 16, color: colors.text,
                valign: 'middle', fontFace: 'Arial',
            })
        } else {
            s.addText(`${prefix}${clean(bullet)}`, {
                x: x, y: yPos, w: 11.7, h: 0.6,
                fontSize: 16, color: colors.text,
                valign: 'middle', fontFace: 'Arial',
            })
        }
        yPos += 0.75
    })
}