import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import PptxGenJS from 'pptxgenjs'
import { SLIDE_TEMPLATES, TemplateId } from '@/lib/slide-templates'

const clean = (text: string): string => {
    if (!text) return ''
    return String(text)
        .replace(/[\x00-\x1F\x7F]/g, '')
        .replace(/[\u{1F300}-\u{1F9FF}]/gu, '')
        .trim()
}

export async function POST(request: NextRequest) {
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const body = await request.json()
    const { templateId, slides, title } = body
    if (!templateId || !slides || !title) return NextResponse.json({ error: 'Missing fields' }, { status: 400 })

    const template = SLIDE_TEMPLATES[templateId as TemplateId] || SLIDE_TEMPLATES.modern

    try {
        const buffer = await generatePPTX(slides, title, template)
        return new NextResponse(new Uint8Array(buffer), {
            headers: {
                'Content-Type': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
                'Content-Disposition': `attachment; filename="${title.replace(/\s+/g, '_')}.pptx"`,
            },
        })
    } catch (error: any) {
        console.error('Export error:', error)
        return NextResponse.json({ error: error.message || 'Failed' }, { status: 500 })
    }
}

// ============================================================
// MAIN GENERATOR - Routes to different layout functions
// ============================================================
async function generatePPTX(slides: any[], title: string, template: any): Promise<Buffer> {
    const pptx = new PptxGenJS()
    pptx.defineLayout({ name: 'WIDE', width: 13.33, height: 7.5 })
    pptx.layout = 'WIDE'

    const layout = template.layout || 'left-bar'
    const colors = template.styles.colors
    const styles = template.styles

    // ===== TITLE SLIDE (varies by layout) =====
    renderTitleSlide(pptx, title, layout, colors, styles)

    // ===== CONTENT SLIDES (switch based on layout) =====
    for (let idx = 0; idx < slides.length; idx++) {
        const slide = slides[idx]
        const s = pptx.addSlide()

        switch (layout) {
            case 'left-bar': renderLeftBarLayout(s, slide, idx, slides.length, colors, styles); break
            case 'top-banner': renderTopBannerLayout(s, slide, idx, slides.length, colors, styles); break
            case 'big-circles': renderBigCirclesLayout(s, slide, idx, slides.length, colors, styles); break
            case 'sidebar': renderSidebarLayout(s, slide, idx, slides.length, colors, styles); break
            case 'hero-center': renderHeroCenterLayout(s, slide, idx, slides.length, colors, styles); break
            case 'blocks': renderBlocksLayout(s, slide, idx, slides.length, colors, styles); break
            case 'numbered': renderNumberedLayout(s, slide, idx, slides.length, colors, styles); break
            case 'split': renderSplitLayout(s, slide, idx, slides.length, colors, styles); break
            default: renderLeftBarLayout(s, slide, idx, slides.length, colors, styles)
        }
    }

    // ===== END SLIDE =====
    const endSlide = pptx.addSlide()
    endSlide.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: 13.33, h: 7.5, fill: { color: colors.accent }, line: { color: colors.accent } })
    endSlide.addText('Thank You', { x: 0.5, y: 2.5, w: 12.33, h: 1.5, fontSize: 54, color: 'FFFFFF', bold: true, align: 'center', valign: 'middle', fontFace: 'Arial' })
    endSlide.addText('Presented by EduGuide AI+', { x: 0.5, y: 4.5, w: 12.33, h: 0.8, fontSize: 20, color: 'FFFFFF', align: 'center', fontFace: 'Arial' })

    const buffer = await pptx.write({ outputType: 'nodebuffer' })
    return buffer as Buffer
}

// ============================================================
// TITLE SLIDE - varies by decoration
// ============================================================
function renderTitleSlide(pptx: any, title: string, layout: string, colors: any, styles: any) {
    const ts = pptx.addSlide()
    ts.background = { color: colors.bg }
    const decoration = styles.titleSlide.decoration

    if (decoration === 'bar') {
        ts.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: 13.33, h: 3, fill: { color: colors.accent }, line: { color: colors.accent } })
        ts.addText(clean(title), { x: 0.5, y: 0.7, w: 12, h: 1.8, fontSize: 44, color: 'FFFFFF', bold: true, align: 'center', valign: 'middle', fontFace: 'Arial' })
        ts.addText('Generated by EduGuide AI+', { x: 0.5, y: 3.7, w: 12.33, h: 1, fontSize: 20, color: colors.text, align: 'center', fontFace: 'Arial' })
        ts.addShape(pptx.ShapeType.rect, { x: 5, y: 5.5, w: 3.33, h: 0.1, fill: { color: colors.accent }, line: { color: colors.accent } })
    } else if (decoration === 'circle') {
        ts.addShape(pptx.ShapeType.ellipse, { x: -1.5, y: -1.5, w: 6, h: 6, fill: { color: colors.secondary }, line: { color: colors.secondary } })
        ts.addShape(pptx.ShapeType.ellipse, { x: 9.5, y: 3.5, w: 5, h: 5, fill: { color: colors.secondary }, line: { color: colors.secondary } })
        ts.addText(clean(title), { x: 0.5, y: 2.5, w: 12.33, h: 2, fontSize: 48, color: colors.text, bold: true, align: 'center', valign: 'middle', fontFace: 'Arial' })
        ts.addText('Generated by EduGuide AI+', { x: 0.5, y: 4.8, w: 12.33, h: 0.8, fontSize: 20, color: colors.text, align: 'center', fontFace: 'Arial' })
    } else if (decoration === 'block') {
        // Big central block
        ts.addShape(pptx.ShapeType.rect, { x: 1.5, y: 1.5, w: 10.33, h: 4.5, fill: { color: colors.accent }, line: { color: colors.accent } })
        ts.addText(clean(title), { x: 1.8, y: 2, w: 9.73, h: 2.5, fontSize: 46, color: 'FFFFFF', bold: true, align: 'center', valign: 'middle', fontFace: 'Arial' })
        ts.addText('Generated by EduGuide AI+', { x: 0.5, y: 6.3, w: 12.33, h: 0.8, fontSize: 18, color: colors.text, align: 'center', fontFace: 'Arial' })
    } else if (decoration === 'diagonal') {
        ts.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: 7, h: 7.5, fill: { color: colors.accent }, line: { color: colors.accent } })
        ts.addText(clean(title), { x: 0.5, y: 2.5, w: 6, h: 2, fontSize: 40, color: 'FFFFFF', bold: true, align: 'left', valign: 'middle', fontFace: 'Arial' })
        ts.addText('Generated by EduGuide AI+', { x: 7.5, y: 3, w: 5.5, h: 1, fontSize: 18, color: colors.text, align: 'left', fontFace: 'Arial' })
    } else {
        // none - minimal
        ts.addText(clean(title), { x: 1, y: 2, w: 11.33, h: 2, fontSize: 44, color: colors.text, bold: true, align: 'left', valign: 'middle', fontFace: 'Arial' })
        ts.addText('Generated by EduGuide AI+', { x: 1, y: 4.2, w: 11.33, h: 0.8, fontSize: 18, color: colors.primary, align: 'left', fontFace: 'Arial' })
        ts.addShape(pptx.ShapeType.rect, { x: 1, y: 5.2, w: 3, h: 0.06, fill: { color: colors.accent }, line: { color: colors.accent } })
    }
}

// ============================================================
// LAYOUT 1: LEFT-BAR (Modern) - Left accent bar + number badge
// ============================================================
function renderLeftBarLayout(s: any, slide: any, idx: number, total: number, colors: any, styles: any) {
    s.background = { color: colors.bg }
    s.addShape('rect', { x: 0, y: 0, w: 0.25, h: 7.5, fill: { color: colors.accent }, line: { color: colors.accent } })
    s.addShape('rect', { x: 0.5, y: 0.5, w: 0.9, h: 0.6, fill: { color: colors.accent }, line: { color: colors.accent } })
    s.addText(String(idx + 1).padStart(2, '0'), { x: 0.5, y: 0.5, w: 0.9, h: 0.6, fontSize: 18, color: 'FFFFFF', bold: true, align: 'center', valign: 'middle', fontFace: 'Arial' })

    const x = 1.7
    s.addText(clean(slide.title), { x, y: 0.5, w: 11, h: 0.9, fontSize: 28, color: colors.text, bold: true, fontFace: 'Arial', valign: 'middle' })
    s.addShape('rect', { x, y: 1.4, w: 1.8, h: 0.06, fill: { color: colors.accent }, line: { color: colors.accent } })

    renderSlideContent(s, slide, colors, styles, x, 2.2, 11)
    renderKeyTakeaway(s, slide, colors, x, 11.8)
    renderSlideNumber(s, idx, total, colors)
}

// ============================================================
// LAYOUT 2: TOP-BANNER (Corporate) - Full top banner with title
// ============================================================
function renderTopBannerLayout(s: any, slide: any, idx: number, total: number, colors: any, styles: any) {
    s.background = { color: colors.bg }
    // Full top banner
    s.addShape('rect', { x: 0, y: 0, w: 13.33, h: 1.4, fill: { color: colors.accent }, line: { color: colors.accent } })
    // Title in banner
    s.addText(clean(slide.title), { x: 0.5, y: 0, w: 11.5, h: 1.4, fontSize: 26, color: 'FFFFFF', bold: true, fontFace: 'Arial', valign: 'middle' })
    // Slide number in banner
    s.addText(`${idx + 1}`, { x: 12.3, y: 0, w: 0.9, h: 1.4, fontSize: 22, color: 'FFFFFF', bold: true, align: 'right', valign: 'middle', fontFace: 'Arial' })

    renderSlideContent(s, slide, colors, styles, 0.7, 1.9, 12)
    renderKeyTakeaway(s, slide, colors, 0.7, 12)
    renderSlideNumber(s, idx, total, colors)
}

// ============================================================
// LAYOUT 3: BIG-CIRCLES (Creative) - Playful circles, centered
// ============================================================
function renderBigCirclesLayout(s: any, slide: any, idx: number, total: number, colors: any, styles: any) {
    s.background = { color: colors.bg }
    // Decorative circles in background
    s.addShape('ellipse', { x: -1.5, y: -1.5, w: 4, h: 4, fill: { color: colors.secondary }, line: { color: colors.secondary } })
    s.addShape('ellipse', { x: 11, y: 5, w: 3.5, h: 3.5, fill: { color: colors.accent }, line: { color: colors.accent } })

    // Title centered
    s.addText(clean(slide.title), { x: 1.5, y: 0.6, w: 10.33, h: 1, fontSize: 30, color: colors.text, bold: true, align: 'center', valign: 'middle', fontFace: 'Arial' })

    // Rounded card behind content
    s.addShape('rect', { x: 1.5, y: 1.9, w: 10.33, h: 4.5, fill: { color: colors.cardBg }, line: { color: colors.accent, width: 1 } })

    renderSlideContent(s, slide, colors, styles, 2.2, 2.2, 9)
    renderKeyTakeaway(s, slide, colors, 1.5, 10.33)
    renderSlideNumber(s, idx, total, colors)
}

// ============================================================
// LAYOUT 4: SIDEBAR (Thesis) - Left colored sidebar (28%) + content
// ============================================================
function renderSidebarLayout(s: any, slide: any, idx: number, total: number, colors: any, styles: any) {
    s.background = { color: colors.bg }
    // Left sidebar full height
    s.addShape('rect', { x: 0, y: 0, w: 3.6, h: 7.5, fill: { color: colors.accent }, line: { color: colors.accent } })
    // Big number
    s.addText(String(idx + 1).padStart(2, '0'), { x: 0.3, y: 0.5, w: 3, h: 1.5, fontSize: 72, color: 'FFFFFF', bold: true, align: 'center', fontFace: 'Arial' })
    // Divider line
    s.addShape('rect', { x: 1, y: 2.4, w: 1.6, h: 0.06, fill: { color: 'FFFFFF' }, line: { color: 'FFFFFF' } })
    // Title inside sidebar (below number)
    s.addText(clean(slide.title), { x: 0.3, y: 2.8, w: 3, h: 3.5, fontSize: 20, color: 'FFFFFF', bold: true, align: 'center', valign: 'top', fontFace: 'Arial' })

    // Content on right side
    renderSlideContent(s, slide, colors, styles, 4.2, 1.5, 8.6)
    renderKeyTakeaway(s, slide, colors, 4.2, 8.6)
    renderSlideNumber(s, idx, total, colors)
}

// ============================================================
// LAYOUT 5: HERO-CENTER (Startup) - Big hero section, centered content
// ============================================================
function renderHeroCenterLayout(s: any, slide: any, idx: number, total: number, colors: any, styles: any) {
    s.background = { color: colors.bg }
    // Hero block at top
    s.addShape('rect', { x: 0, y: 0, w: 13.33, h: 2.2, fill: { color: colors.accent }, line: { color: colors.accent } })
    // Big centered title
    s.addText(clean(slide.title), { x: 0.5, y: 0, w: 12.33, h: 2.2, fontSize: 36, color: 'FFFFFF', bold: true, align: 'center', valign: 'middle', fontFace: 'Arial' })

    // Content centered
    renderSlideContent(s, slide, colors, styles, 1.5, 3, 10.33)
    renderKeyTakeaway(s, slide, colors, 1.5, 10.33)
    renderSlideNumber(s, idx, total, colors)
}

// ============================================================
// LAYOUT 6: BLOCKS (SaaS/Product) - Content in bordered cards
// ============================================================
function renderBlocksLayout(s: any, slide: any, idx: number, total: number, colors: any, styles: any) {
    s.background = { color: colors.bg }
    // Small header
    s.addShape('rect', { x: 0, y: 0, w: 13.33, h: 0.9, fill: { color: colors.accent }, line: { color: colors.accent } })
    s.addText(clean(slide.title), { x: 0.5, y: 0, w: 11, h: 0.9, fontSize: 22, color: 'FFFFFF', bold: true, fontFace: 'Arial', valign: 'middle' })
    s.addText(String(idx + 1).padStart(2, '0'), { x: 11.5, y: 0, w: 1.5, h: 0.9, fontSize: 16, color: 'FFFFFF', bold: true, align: 'right', valign: 'middle', fontFace: 'Arial' })

    // Blocks of content - each bullet in its own card
    const bullets = (slide.bullets || []).slice(0, 4)
    bullets.forEach((bullet: string, i: number) => {
        const bY = 1.3 + i * 1.35
        s.addShape('rect', { x: 0.7, y: bY, w: 12, h: 1.2, fill: { color: colors.cardBg }, line: { color: colors.accent, width: 0.5 } })
        // Number/icon at left
        s.addShape('ellipse', { x: 0.9, y: bY + 0.25, w: 0.7, h: 0.7, fill: { color: colors.accent }, line: { color: colors.accent } })
        s.addText(String(i + 1), { x: 0.9, y: bY + 0.25, w: 0.7, h: 0.7, fontSize: 16, color: 'FFFFFF', bold: true, align: 'center', valign: 'middle', fontFace: 'Arial' })
        // Text
        s.addText(clean(bullet).substring(0, 160), { x: 1.8, y: bY + 0.1, w: 10.7, h: 1, fontSize: 12, color: colors.text, valign: 'middle', fontFace: 'Arial' })
    })

    renderKeyTakeaway(s, slide, colors, 0.7, 12)
    renderSlideNumber(s, idx, total, colors)
}

// ============================================================
// LAYOUT 7: NUMBERED (Academic) - Big number + text side by side
// ============================================================
function renderNumberedLayout(s: any, slide: any, idx: number, total: number, colors: any, styles: any) {
    s.background = { color: colors.bg }
    // Header
    s.addText(clean(slide.title), { x: 0.7, y: 0.5, w: 11.9, h: 1, fontSize: 28, color: colors.text, bold: true, align: 'left', fontFace: 'Arial', valign: 'middle' })
    s.addShape('rect', { x: 0.7, y: 1.6, w: 2.5, h: 0.06, fill: { color: colors.accent }, line: { color: colors.accent } })

    // Content as numbered items (big number + text)
    const bullets = (slide.bullets || []).slice(0, 6)
    bullets.forEach((bullet: string, i: number) => {
        const y = 2.2 + i * 0.75
        // Big number
        s.addText(String(i + 1), { x: 0.7, y, w: 0.8, h: 0.65, fontSize: 32, color: colors.accent, bold: true, align: 'center', valign: 'middle', fontFace: 'Arial' })
        // Small vertical line
        s.addShape('rect', { x: 1.55, y: y + 0.1, w: 0.04, h: 0.5, fill: { color: colors.accent }, line: { color: colors.accent } })
        // Text
        s.addText(clean(bullet), { x: 1.8, y, w: 10.8, h: 0.65, fontSize: 13, color: colors.text, valign: 'middle', fontFace: 'Arial' })
    })

    renderKeyTakeaway(s, slide, colors, 0.7, 12)
    renderSlideNumber(s, idx, total, colors)
}

// ============================================================
// LAYOUT 8: SPLIT (UX/Report) - Left title, right content split
// ============================================================
function renderSplitLayout(s: any, slide: any, idx: number, total: number, colors: any, styles: any) {
    s.background = { color: colors.bg }
    // Left column (40%) - title block
    s.addShape('rect', { x: 0, y: 0, w: 5.33, h: 7.5, fill: { color: colors.accent }, line: { color: colors.accent } })
    // Number
    s.addText(String(idx + 1).padStart(2, '0'), { x: 0.5, y: 0.5, w: 4.33, h: 1, fontSize: 24, color: 'FFFFFF', bold: true, fontFace: 'Arial' })
    // Title in left column
    s.addText(clean(slide.title), { x: 0.5, y: 2, w: 4.33, h: 3.5, fontSize: 26, color: 'FFFFFF', bold: true, valign: 'top', fontFace: 'Arial' })
    // Decorative line
    s.addShape('rect', { x: 0.5, y: 6, w: 2, h: 0.06, fill: { color: 'FFFFFF' }, line: { color: 'FFFFFF' } })

    // Right column (60%) - content
    renderSlideContent(s, slide, colors, styles, 6, 1.5, 6.8)
    renderKeyTakeaway(s, slide, colors, 6, 6.8)
    renderSlideNumber(s, idx, total, colors)
}

// ============================================================
// SHARED: Slide content renderer (handles type-based layouts)
// ============================================================
function renderSlideContent(s: any, slide: any, colors: any, styles: any, x: number, y: number, w: number) {
    const type = slide.type || 'content'

    switch (type) {
        case 'chart': return renderChart(s, slide, colors, x, y, w)
        case 'stats': return renderStats(s, slide, colors, x, y, w)
        case 'process': return renderProcess(s, slide, colors, x, y, w)
        case 'comparison': return renderComparison(s, slide, colors, x, y, w)
        case 'quote': return renderQuote(s, slide, colors, x, y, w)
        case 'icon-grid': return renderIconGrid(s, slide, colors, x, y, w)
        default: return renderBullets(s, slide, colors, styles, x, y, w)
    }
}

function renderBullets(s: any, slide: any, colors: any, styles: any, x: number, y: number, w: number) {
    const bullets = (slide.bullets || ['No content']).slice(0, 7)
    const bs = styles.contentSlide.bulletStyle
    let prefix = '• '
    if (bs === 'arrow') prefix = '▸ '
    else if (bs === 'check') prefix = '✓ '
    else if (bs === 'square') prefix = '▪ '

    let cy = y
    bullets.forEach((bullet: string, i: number) => {
        const p = bs === 'number' ? `${i + 1}. ` : prefix
        s.addText(`${p}${clean(bullet)}`, { x, y: cy, w, h: 0.6, fontSize: 14, color: colors.text, valign: 'middle', fontFace: 'Arial', align: styles.contentSlide.alignment })
        cy += 0.7
    })
}

function renderChart(s: any, slide: any, colors: any, x: number, y: number, w: number) {
    const data = (slide.chartData || []).slice(0, 8)
    if (!data.length) return
    let type = 'bar'
    if (slide.chartType === 'pie') type = 'pie'
    else if (slide.chartType === 'line') type = 'line'
    else if (slide.chartType === 'doughnut') type = 'doughnut'

    s.addChart(type, [{ name: clean(slide.title || 'Data'), labels: data.map((d: any) => clean(d.label)), values: data.map((d: any) => Number(d.value) || 0) }], {
        x, y, w, h: 3.8, showLegend: true, legendPos: 'b', showValue: true,
        chartColors: [colors.accent, colors.secondary, colors.primary, '6366F1', 'EC4899', 'F97316', '10B981', '8B5CF6'],
    })
}

function renderStats(s: any, slide: any, colors: any, x: number, y: number, w: number) {
    const stats = (slide.stats || []).slice(0, 4)
    if (!stats.length) return
    const gap = 0.3, cw = (w - gap * (stats.length - 1)) / stats.length
    stats.forEach((st: any, i: number) => {
        const cx = x + i * (cw + gap)
        s.addShape('rect', { x: cx, y, w: cw, h: 2.8, fill: { color: colors.cardBg }, line: { color: colors.accent, width: 1 } })
        s.addShape('rect', { x: cx, y, w: cw, h: 0.15, fill: { color: colors.accent }, line: { color: colors.accent } })
        s.addText(clean(st.value || '0'), { x: cx, y: y + 0.5, w: cw, h: 1.3, fontSize: 48, color: colors.accent, bold: true, align: 'center', valign: 'middle', fontFace: 'Arial' })
        s.addText(clean(st.label || ''), { x: cx + 0.15, y: y + 1.9, w: cw - 0.3, h: 0.8, fontSize: 12, color: colors.text, align: 'center', valign: 'middle', fontFace: 'Arial' })
    })
}

function renderProcess(s: any, slide: any, colors: any, x: number, y: number, w: number) {
    const steps = (slide.steps || []).slice(0, 5)
    if (!steps.length) return
    const cs = 0.9, gap = (w - cs * steps.length) / (steps.length + 1)
    const yc = y + 1.5
    steps.forEach((step: string, i: number) => {
        const cx = x + gap + i * (cs + gap)
        s.addShape('ellipse', { x: cx, y: yc, w: cs, h: cs, fill: { color: colors.accent }, line: { color: colors.accent } })
        s.addText(String(i + 1), { x: cx, y: yc, w: cs, h: cs, fontSize: 26, color: 'FFFFFF', bold: true, align: 'center', valign: 'middle', fontFace: 'Arial' })
        s.addText(clean(step), { x: cx - 0.5, y: yc + cs + 0.2, w: cs + 1, h: 1.5, fontSize: 11, color: colors.text, align: 'center', valign: 'top', fontFace: 'Arial' })
    })
}

function renderComparison(s: any, slide: any, colors: any, x: number, y: number, w: number) {
    const halfW = (w - 0.6) / 2
        ;['left', 'right'].forEach((side: string, si: number) => {
            const cx = x + si * (halfW + 0.6)
            const title = si === 0 ? slide.leftTitle : slide.rightTitle
            const items = (si === 0 ? slide.leftItems : slide.rightItems) || []
            const col = si === 0 ? colors.accent : colors.secondary

            s.addShape('rect', { x: cx, y, w: halfW, h: 3.8, fill: { color: colors.cardBg }, line: { color: col, width: 1 } })
            s.addShape('rect', { x: cx, y, w: halfW, h: 0.7, fill: { color: col }, line: { color: col } })
            s.addText(clean(title || ''), { x: cx, y, w: halfW, h: 0.7, fontSize: 16, color: 'FFFFFF', bold: true, align: 'center', valign: 'middle', fontFace: 'Arial' })
            items.slice(0, 6).forEach((it: string, i: number) => {
                s.addText(`• ${clean(it)}`, { x: cx + 0.2, y: y + 0.85 + i * 0.5, w: halfW - 0.4, h: 0.5, fontSize: 11, color: colors.text, valign: 'middle', fontFace: 'Arial' })
            })
        })
}

function renderQuote(s: any, slide: any, colors: any, x: number, y: number, w: number) {
    s.addText('"', { x: x - 0.2, y: y, w: 2, h: 2, fontSize: 96, color: colors.accent, bold: true, align: 'left', valign: 'top', fontFace: 'Arial' })
    s.addText(clean(slide.quote || ''), { x: x + 0.8, y: y + 0.8, w: w - 1.6, h: 2.5, fontSize: 20, color: colors.text, italic: true, align: 'center', valign: 'middle', fontFace: 'Arial' })
    if (slide.author) {
        s.addText(`— ${clean(slide.author)}`, { x: x + 0.8, y: y + 3.5, w: w - 1.6, h: 0.5, fontSize: 14, color: colors.accent, bold: true, align: 'center', fontFace: 'Arial' })
    }
}

function renderIconGrid(s: any, slide: any, colors: any, x: number, y: number, w: number) {
    const items = (slide.items || []).slice(0, 6)
    if (!items.length) return
    const cols = 3, cw = (w - 0.6) / cols, ch = 1.4
    items.forEach((it: any, i: number) => {
        const row = Math.floor(i / cols), col = i % cols
        const cx = x + col * (cw + 0.3)
        const cy = y + row * (ch + 0.2)
        s.addShape('rect', { x: cx, y: cy, w: cw, h: ch, fill: { color: colors.cardBg }, line: { color: colors.accent, width: 1 } })
        s.addShape('ellipse', { x: cx + 0.15, y: cy + 0.35, w: 0.7, h: 0.7, fill: { color: colors.accent }, line: { color: colors.accent } })
        s.addText(clean(it.icon || '●'), { x: cx + 0.15, y: cy + 0.35, w: 0.7, h: 0.7, fontSize: 20, color: 'FFFFFF', bold: true, align: 'center', valign: 'middle', fontFace: 'Arial' })
        s.addText(clean(it.label || ''), { x: cx + 0.9, y: cy, w: cw - 1, h: ch, fontSize: 11, color: colors.text, bold: true, valign: 'middle', fontFace: 'Arial' })
    })
}

// ============================================================
// SHARED: Key Takeaway + Slide Number
// ============================================================
function renderKeyTakeaway(s: any, slide: any, colors: any, x: number, w: number) {
    if (!slide.key_takeaway) return
    s.addShape('rect', { x, y: 6.55, w, h: 0.6, fill: { color: 'FEF3C7' }, line: { color: colors.accent, width: 0.5 } })
    s.addText(`TIP: ${clean(slide.key_takeaway)}`, { x: x + 0.2, y: 6.55, w: w - 0.4, h: 0.6, fontSize: 10, color: '92400E', italic: true, valign: 'middle', fontFace: 'Arial' })
}

function renderSlideNumber(s: any, idx: number, total: number, colors: any) {
    s.addText(`${idx + 1} / ${total}`, { x: 11.5, y: 7.2, w: 1.5, h: 0.3, fontSize: 10, color: '9CA3AF', align: 'right', fontFace: 'Arial' })
}